export const GET_PATIENTS = "GET_PATIENTS";
export const EDIT_PATIENT = "EDIT_PATIENT";
export const ADD_PATIENT = "ADD_PATIENT";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const PATIENTS_LOADING = "PATIENTS_LOADING";
