export const GET_DIAGNOSTICS = "GET_DIAGNOSTICS";
export const ADD_DIAGNOSTIC = "ADD_DIAGNOSTIC";
export const EDIT_DIAGNOSTIC = "EDIT_DIAGNOSTIC";
export const DELETE_DIAGNOSTIC = "DELETE_DIAGNOSTIC";
export const GENERATE_DIAGNOSTICS = "GENERATE_DIAGNOSTICS";
export const DIAGNOSTICS_LOADING = "DIAGNOSTICS_LOADING";
